---
- hosts: localhost
  remote_user: ubuntu
  gather_facts: yes
  tasks:
    - name: Set manager
      set_fact:
        manager: "{{ ansible_facts.default_ipv4.address }}"
    - name: Manager IP
      debug:
        msg: "{{ manager }}"
    - name: tg_hosts
      debug:
        msg: "{{ groups[tg_hosts] }}"
    - name: Set new_hosts
      set_fact:
        new_hosts: "{{ [ manager ] | union(groups[tg_hosts]) }}"
        manager: "{{ ansible_facts.default_ipv4.address }}"
    - name: tg_hosts reordered
      debug:
        msg: "{{ new_hosts }}"
    - name: generate inventory file from template
      template:
        src: inventory.ini.j2
        dest: inventory.ini
