---
- hosts: localhost
  become: yes
  tasks:
    - name: copy redis.conf
      copy:
        src: redis.conf
        dest: /etc/redis/redis.conf
        owner: redis
        group: redis
        mode: 0600
    - name: ensure redis is running
      systemd:
        name: redis-server
        enabled: yes
        state: started
